/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    scala
}
repositories {
    mavenCentral()
}
dependencies {
    implementation("org.scala-lang:scala-library:2.13.2")
}